name: BuildTasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, task0, task1, task2, task3, task4, task5, task6, task7, task10, task11, task12 ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install_glfw    
      run: |
        sudo apt-get update
        sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        sudo apt-get install libxmu-dev xorg-dev
        sudo apt-get install libglfw3-dev 
        sudo apt-get install libopenal-dev
        sudo apt-get install libgl1-mesa-dev

    - name: get_delfem2
      run: |
        git submodule update --init -- 3rd_party/glfw
        cd 3rd_party/glfw
        cmake .
        cmake --build .

    - name: get_delfem2
      run: |
        git submodule update --init -- 3rd_party/delfem2

    - name: build
      run: |
        cmake .
        cmake --build .
